### PR TITLE
Feature: Add option for single triggered job

### PR DESCRIPTION
**Pull request by solarlodge**
### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
```

### CODE REVIEW

**Comment by cdelmonte-zg** [comment]
@solarlodge thank you for the PR. can you tell me something more about this feature? Tnx

**Comment by solarlodge** [comment]
@cdelmonte-zg You're right. Added this to to docs.

**Review by cdelmonte-zg — APPROVED** [review]

**Comment by cdelmonte-zg** [comment]
Hi @solarlodge, is your jenkins version >= 2.361.4? I'm asking because I'm updating the plugin to work with Java 17
and I'd like to release the features you've introduced with version 3.0.0 later this week.

Otherwise, if your Jenkins version is < 2.361.4, I'll schedule an extra release, say the 2.9.0, before I release the 3.0.0.

**Comment by solarlodge** [comment]
@cdelmonte-zg It's Jenkins 2.414.2 (LTS). According to the [jenkins java support policy](https://www.jenkins.io/doc/book/platform-information/support-policy-java/) it shouldn't be an issue :)

**Pull request merged**
